// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('fixture test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('fixture test', async function() {
    // Test name: fixture test
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:8000/")
    // 2 | setWindowSize | 1366x728 | 
    await driver.manage().window().setRect({ width: 1366, height: 728 })
    // 3 | click | linkText=Log in | 
    await driver.findElement(By.linkText("Log in")).click()
    // 4 | click | linkText=Fixture | 
    await driver.findElement(By.linkText("Fixture")).click()
    // 5 | click | css=.tracking-wide | 
    await driver.findElement(By.css(".tracking-wide")).click()
    // 6 | click | name=tournament_id | 
    await driver.findElement(By.name("tournament_id")).click()
    // 7 | select | name=tournament_id | label=torneo 6
    {
      const dropdown = await driver.findElement(By.name("tournament_id"))
      await dropdown.findElement(By.xpath("//option[. = 'torneo 6']")).click()
    }
    // 8 | click | name=local | 
    await driver.findElement(By.name("local")).click()
    // 9 | select | name=local | label=blanco
    {
      const dropdown = await driver.findElement(By.name("local"))
      await dropdown.findElement(By.xpath("//option[. = 'blanco']")).click()
    }
    // 10 | click | name=visitor | 
    await driver.findElement(By.name("visitor")).click()
    // 11 | select | name=visitor | label=rosa
    {
      const dropdown = await driver.findElement(By.name("visitor"))
      await dropdown.findElement(By.xpath("//option[. = 'rosa']")).click()
    }
    // 12 | click | css=.flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300 | 
    await driver.findElement(By.css(".flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300")).click()
    // 13 | click | css=.flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300 | 
    await driver.findElement(By.css(".flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300")).click()
    // 14 | click | css=.flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300 | 
    await driver.findElement(By.css(".flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300")).click()
    // 15 | click | css=.flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300 | 
    await driver.findElement(By.css(".flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300")).click()
    // 16 | type | css=.flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300 | 2024-05-04T02:01
    await driver.findElement(By.css(".flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300")).sendKeys("2024-05-04T02:01")
    // 17 | click | name=place_id | 
    await driver.findElement(By.name("place_id")).click()
    // 18 | select | name=place_id | label=cono norte
    {
      const dropdown = await driver.findElement(By.name("place_id"))
      await dropdown.findElement(By.xpath("//option[. = 'cono norte']")).click()
    }
    // 19 | click | css=.flex:nth-child(4) .border-gray-300 | 
    await driver.findElement(By.css(".flex:nth-child(4) .border-gray-300")).click()
    // 20 | select | css=.flex:nth-child(4) .border-gray-300 | label=Iniciado
    {
      const dropdown = await driver.findElement(By.css(".flex:nth-child(4) .border-gray-300"))
      await dropdown.findElement(By.xpath("//option[. = 'Iniciado']")).click()
    }
    // 21 | click | css=.flex:nth-child(4) .border-gray-300 | 
    await driver.findElement(By.css(".flex:nth-child(4) .border-gray-300")).click()
    // 22 | select | css=.flex:nth-child(4) .border-gray-300 | label=Programado
    {
      const dropdown = await driver.findElement(By.css(".flex:nth-child(4) .border-gray-300"))
      await dropdown.findElement(By.xpath("//option[. = 'Programado']")).click()
    }
    // 23 | click | css=.bg-gray-800:nth-child(2) | 
    await driver.findElement(By.css(".bg-gray-800:nth-child(2)")).click()
    // 24 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 25 | click | css=.text-sm:nth-child(5) .inline-flex:nth-child(1) > .fas | 
    await driver.findElement(By.css(".text-sm:nth-child(5) .inline-flex:nth-child(1) > .fas")).click()
    // 26 | click | name=tournament_id | 
    await driver.findElement(By.name("tournament_id")).click()
    // 27 | click | name=tournament_id | 
    await driver.findElement(By.name("tournament_id")).click()
    // 28 | click | name=tournament_id | 
    await driver.findElement(By.name("tournament_id")).click()
    // 29 | select | name=tournament_id | label=torneo 9
    {
      const dropdown = await driver.findElement(By.name("tournament_id"))
      await dropdown.findElement(By.xpath("//option[. = 'torneo 9']")).click()
    }
    // 30 | click | name=tournament_id | 
    await driver.findElement(By.name("tournament_id")).click()
    // 31 | click | css=.flex-row | 
    await driver.findElement(By.css(".flex-row")).click()
    // 32 | click | name=visitor | 
    await driver.findElement(By.name("visitor")).click()
    // 33 | select | name=visitor | label=violeta
    {
      const dropdown = await driver.findElement(By.name("visitor"))
      await dropdown.findElement(By.xpath("//option[. = 'violeta']")).click()
    }
    // 34 | click | name=visitor | 
    await driver.findElement(By.name("visitor")).click()
    // 35 | select | name=visitor | label=rosa
    {
      const dropdown = await driver.findElement(By.name("visitor"))
      await dropdown.findElement(By.xpath("//option[. = 'rosa']")).click()
    }
    // 36 | click | name=visitor | 
    await driver.findElement(By.name("visitor")).click()
    // 37 | select | name=visitor | label=violeta
    {
      const dropdown = await driver.findElement(By.name("visitor"))
      await dropdown.findElement(By.xpath("//option[. = 'violeta']")).click()
    }
    // 38 | click | css=.flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300 | 
    await driver.findElement(By.css(".flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300")).click()
    // 39 | type | css=.flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300 | 2024-05-04T05:01
    await driver.findElement(By.css(".flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300")).sendKeys("2024-05-04T05:01")
    // 40 | click | css=.bg-gray-800:nth-child(2) | 
    await driver.findElement(By.css(".bg-gray-800:nth-child(2)")).click()
    // 41 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 42 | click | css=.text-sm:nth-child(5) .inline-flex:nth-child(2) > .fas | 
    await driver.findElement(By.css(".text-sm:nth-child(5) .inline-flex:nth-child(2) > .fas")).click()
    // 43 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 44 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
  })
})
