// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('sorteo test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('sorteo test', async function() {
    // Test name: sorteo test
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:8000/")
    // 2 | setWindowSize | 1366x728 | 
    await driver.manage().window().setRect({ width: 1366, height: 728 })
    // 3 | click | linkText=Log in | 
    await driver.findElement(By.linkText("Log in")).click()
    // 4 | click | linkText=Sorteo | 
    await driver.findElement(By.linkText("Sorteo")).click()
    // 5 | click | css=.hover\3A bg-blue-700 | 
    await driver.findElement(By.css(".hover\\3A bg-blue-700")).click()
    // 6 | click | css=.bg-red-500 | 
    await driver.findElement(By.css(".bg-red-500")).click()
    // 7 | click | css=.hover\3A bg-blue-700 | 
    await driver.findElement(By.css(".hover\\3A bg-blue-700")).click()
    // 8 | type | name=timegame | 29
    await driver.findElement(By.name("timegame")).sendKeys("29")
    // 9 | click | name=timegame | 
    await driver.findElement(By.name("timegame")).click()
    // 10 | type | name=timegame | 28
    await driver.findElement(By.name("timegame")).sendKeys("28")
    // 11 | click | name=timegame | 
    await driver.findElement(By.name("timegame")).click()
    // 12 | type | name=timegame | 27
    await driver.findElement(By.name("timegame")).sendKeys("27")
    // 13 | click | name=timegame | 
    await driver.findElement(By.name("timegame")).click()
    // 14 | doubleClick | name=timegame | 
    {
      const element = await driver.findElement(By.name("timegame"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 15 | type | name=timegame | 26
    await driver.findElement(By.name("timegame")).sendKeys("26")
    // 16 | click | name=timegame | 
    await driver.findElement(By.name("timegame")).click()
    // 17 | type | name=timegame | 25
    await driver.findElement(By.name("timegame")).sendKeys("25")
    // 18 | click | name=timegame | 
    await driver.findElement(By.name("timegame")).click()
    // 19 | doubleClick | name=timegame | 
    {
      const element = await driver.findElement(By.name("timegame"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 20 | click | name=timegame | 
    await driver.findElement(By.name("timegame")).click()
    // 21 | click | name=timegame | 
    await driver.findElement(By.name("timegame")).click()
    // 22 | type | name=timegame | 24
    await driver.findElement(By.name("timegame")).sendKeys("24")
    // 23 | click | name=timegame | 
    await driver.findElement(By.name("timegame")).click()
    // 24 | type | name=timegame | 23
    await driver.findElement(By.name("timegame")).sendKeys("23")
    // 25 | click | name=timegame | 
    await driver.findElement(By.name("timegame")).click()
    // 26 | doubleClick | name=timegame | 
    {
      const element = await driver.findElement(By.name("timegame"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 27 | click | css=.hover\3A bg-blue-700 | 
    await driver.findElement(By.css(".hover\\3A bg-blue-700")).click()
    // 28 | click | css=div:nth-child(1) > .bg-gray-50 | 
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).click()
    // 29 | type | css=div:nth-child(1) > .bg-gray-50 | 0002-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("0002-11-04")
    // 30 | type | css=div:nth-child(1) > .bg-gray-50 | 0020-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("0020-11-04")
    // 31 | type | css=div:nth-child(1) > .bg-gray-50 | 0202-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("0202-11-04")
    // 32 | type | css=div:nth-child(1) > .bg-gray-50 | 0004-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("0004-11-04")
    // 33 | type | css=div:nth-child(1) > .bg-gray-50 | 0002-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("0002-11-04")
    // 34 | type | css=div:nth-child(1) > .bg-gray-50 | 0020-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("0020-11-04")
    // 35 | type | css=div:nth-child(1) > .bg-gray-50 | 0002-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("0002-11-04")
    // 36 | type | css=div:nth-child(1) > .bg-gray-50 | 0002-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("0002-11-04")
    // 37 | type | css=div:nth-child(1) > .bg-gray-50 | 0002-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("0002-11-04")
    // 38 | type | css=div:nth-child(1) > .bg-gray-50 | 0020-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("0020-11-04")
    // 39 | type | css=div:nth-child(1) > .bg-gray-50 | 0203-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("0203-11-04")
    // 40 | type | css=div:nth-child(1) > .bg-gray-50 | 0002-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("0002-11-04")
    // 41 | type | css=div:nth-child(1) > .bg-gray-50 | 0003-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("0003-11-04")
    // 42 | type | css=div:nth-child(1) > .bg-gray-50 | 0032-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("0032-11-04")
    // 43 | type | css=div:nth-child(1) > .bg-gray-50 | 0323-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("0323-11-04")
    // 44 | type | css=div:nth-child(1) > .bg-gray-50 | 3232-11-04
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("3232-11-04")
    // 45 | click | css=.bg-red-500 | 
    await driver.findElement(By.css(".bg-red-500")).click()
    // 46 | click | name=timeinit | 
    await driver.findElement(By.name("timeinit")).click()
    // 47 | click | name=timeinit | 
    await driver.findElement(By.name("timeinit")).click()
    // 48 | type | name=timeinit | 09:00
    await driver.findElement(By.name("timeinit")).sendKeys("09:00")
    // 49 | type | name=timeinit | 09:09
    await driver.findElement(By.name("timeinit")).sendKeys("09:09")
    // 50 | click | css=.bg-red-500 | 
    await driver.findElement(By.css(".bg-red-500")).click()
    // 51 | click | css=.bg-white:nth-child(1) > td > .w-40 | 
    await driver.findElement(By.css(".bg-white:nth-child(1) > td > .w-40")).click()
  })
})
